export const DEFAULT_STOCK_SYMBOLS = [
  'AAPL','MSFT','NVDA','AMZN','GOOGL','META','TSLA','AVGO','AMD','NFLX','ORCL','CRM','ADBE','INTC','QCOM','ARM','PLTR','SNOW','SHOP','UBER',
  'ABNB','COIN','HOOD','SOFI','JPM','BAC','GS','MS','V','MA','PYPL','AXP','WMT','COST','PG','KO','PEP','MCD','NKE','SBUX',
  'XOM','CVX','SLB','COP','LLY','JNJ','MRK','PFE','UNH','ABBV','CAT','GE','BA','RTX','DE','DIS','SONY','TM','SAP','ASML',
  'AMAT','LRCX','KLAC','MU','TXN','ADI','PANW','CRWD','ZS','NET','DDOG','MDB','NOW','TEAM','INTU','ANET','WDAY','SQ','RBLX','TTD',
  'MELI','SE','BABA','PDD','JD','TCEHY','NIO','RIVN','LCID','F','GM','RACE','MBLY','STLA','VZ','T','TMUS','CMCSA','CHTR','ATVI',
  'EA','U','ROKU','SPOT','LYFT','DASH','CVNA','BKNG','EXPE','MAR','HLT','DAL','UAL','AAL','LUV','CSCO','IBM','HPQ','DELL','HPE',
  'CSX','UNP','NSC','FDX','UPS','ETN','HON','MMM','PH','ITW','EMR','LMT','NOC','GD','HII','C','SCHW','BLK','BX','KKR',
  'CME','ICE','CB','AIG','PGR','TRV','ALL','BK','USB','PNC','TFC','WFC','COF','DFS','MSCI','SPGI','MCO','ADP','PAYX','FIS',
  'GPN','FISV','TTWO','AMGN','GILD','BIIB','REGN','VRTX','ISRG','SYK','BSX','MDT','ABT','DHR','TMO','BMY','ZTS','CVS','CI','HUM',
  'LOW','HD','TGT','KR','DG','DLTR','KHC','CL','KMB','MDLZ','GIS','CPB','HSY','MNST','KDP','PM','MO','EL','UL','RIO',
  'BHP','FCX','NEM','GOLD','NUE','STLD','X','MP','LULU','ETSY','PINS','SNAP','PTON','DOCU','ZM','OKTA','TWLO','SMCI','ENPH','SEDG',
  'FSLR','NEE','DUK','SO','AEP','XEL','EIX','EXC','SRE','PCG','MSTR','RIOT','MARA','BITF','CLSK','HUT','IBIT','GBTC','ARKB','BITO',
];

export const DEFAULT_ETF_SYMBOLS = [
  'SPY','VOO','IVV','VTI','QQQ','VUG','SCHD','DIA','IWM','XLK','XLF','XLE','XLV','XLY','XLI','XLP','XLC','XLU','XLB','XLRE',
  'SMH','ARKK','SOXX','GLD','SLV','IAU','TLT','IEF','SHY','BND','AGG','LQD','HYG','VNQ','VEA','VWO','EEM','SCHG','SPLG','VYM',
  'VO','VB','IJH','IJR','SCHB','ITOT','SCHF','VXUS','BIL','SGOV','TIP','SCHP','MBB','BNDX','EMB','MINT','USFR','TFLO','RSP','SPYG',
  'SPYD','SPDW','SPAB','VT','ACWI','URTH','QQQM','IVW','IWF','IWD','IWN','IWO','IWB','IWR','IWP','IWS','MTUM','QUAL','USMV','VLUE',
  'SIZE','VTV','VEU','IEFA','EWJ','EWZ','EWT','FXI','KWEB','ASHR','XBI','IBB','XRT','XHB','XOP','KRE','XME','ITA','PHO','ICLN',
  'TAN','LIT','PAVE','BOTZ','ROBO','CLOU','SKYY','IGV','FDN','XAR','GDX','GDXJ','DBC','UUP','UNG','USO','SVIX','VIXY','SQQQ','TQQQ',
  'SPXS','SPXL','UVXY','BITO','BTF','ARKF','ARKQ','ARKW','ARKG','FDIS','VHT','VFH','VDE','VIS','VAW','VPU','VOX','IYR','SCHH','REM',
];

export const DEFAULT_CRYPTO_SYMBOLS = [
  'BINANCE:BTCUSDT','BINANCE:ETHUSDT','BINANCE:SOLUSDT','BINANCE:XRPUSDT','BINANCE:BNBUSDT','BINANCE:ADAUSDT','BINANCE:AVAXUSDT','BINANCE:DOGEUSDT','BINANCE:LINKUSDT','BINANCE:DOTUSDT',
  'BINANCE:MATICUSDT','BINANCE:POLUSDT','BINANCE:LTCUSDT','BINANCE:BCHUSDT','BINANCE:UNIUSDT','BINANCE:ATOMUSDT','BINANCE:NEARUSDT','BINANCE:APTUSDT','BINANCE:ARBUSDT','BINANCE:OPUSDT',
  'BINANCE:ETCUSDT','BINANCE:FILUSDT','BINANCE:ICPUSDT','BINANCE:INJUSDT','BINANCE:TONUSDT','BINANCE:TRXUSDT','BINANCE:HBARUSDT','BINANCE:VETUSDT','BINANCE:ALGOUSDT','BINANCE:AAVEUSDT',
  'BINANCE:RNDRUSDT','BINANCE:SUIUSDT','BINANCE:SEIUSDT','BINANCE:SHIBUSDT','BINANCE:PEPEUSDT','BINANCE:WIFUSDT','BINANCE:BONKUSDT','BINANCE:IMXUSDT','BINANCE:STXUSDT','BINANCE:TIAUSDT',
  'BINANCE:PYTHUSDT','BINANCE:JUPUSDT','BINANCE:ONDOUSDT','BINANCE:MKRUSDT','BINANCE:COMPUSDT','BINANCE:SNXUSDT','BINANCE:GRTUSDT','BINANCE:FLOWUSDT','BINANCE:EGLDUSDT','BINANCE:THETAUSDT',
  'BINANCE:XLMUSDT','BINANCE:XMRUSDT','BINANCE:KASUSDT','BINANCE:TAOUSDT','BINANCE:RENDERUSDT','BINANCE:ENAUSDT','BINANCE:WLDUSDT','BINANCE:BATUSDT','BINANCE:ZECUSDT','BINANCE:NEOUSDT',
  'BINANCE:DASHUSDT','BINANCE:CRVUSDT','BINANCE:LDOUSDT','BINANCE:RUNEUSDT','BINANCE:AXSUSDT','BINANCE:SANDUSDT','BINANCE:MANAUSDT','BINANCE:APEUSDT','BINANCE:CHZUSDT','BINANCE:HOTUSDT',
];

export const DEFAULT_INDEX_SYMBOLS = ['SPX', 'NDX', 'DJI', 'VIX', '^GSPC', '^IXIC', '^DJI', '^VIX'];
