import type { MarketAssetKind, MarketHistoryResolution, ProviderQuoteMode } from './types';

export type ProviderAuthMode = 'none' | 'api-key' | 'hmac';
export type ProviderReliabilityTier = 'experimental' | 'standard' | 'high';
export type UnifiedProviderId =
  | 'binance'
  | 'bybit'
  | 'okx'
  | 'coinbase'
  | 'finnhub'
  | 'polygon'
  | 'twelve-data'
  | 'coingecko'
  | 'eodhd'
  | 'tiingo'
  | 'world-bank'
  | 'ecb'
  | 'fred'
  | 'local-cache';

export type ProviderCapabilities = {
  providerId: UnifiedProviderId;
  displayName: string;
  authMode: ProviderAuthMode;
  assetClasses: MarketAssetKind[];
  supportsRest: boolean;
  supportsWebSocket: boolean;
  supportsAuthenticatedAccount: boolean;
  supportsSpot: boolean;
  supportsPerpetuals: boolean;
  supportsFutures: boolean;
  supportsFundingRates: boolean;
  supportsOpenInterest: boolean;
  supportsLiquidations: boolean;
  supportsOrderBook: boolean;
  supportsTrades: boolean;
  supportsCandles: boolean;
  supportsTickers: boolean;
  supportsHistorical: boolean;
  supportedIntervals: MarketHistoryResolution[];
  quoteMode: ProviderQuoteMode;
  rateLimitProfile: string;
  dataFreshnessProfile: string;
  reliabilityTier: ProviderReliabilityTier;
  notes: string;
};

const CAPS: Record<UnifiedProviderId, ProviderCapabilities> = {
  binance: {
    providerId: 'binance',
    displayName: 'Binance',
    authMode: 'hmac',
    assetClasses: ['crypto'],
    supportsRest: true,
    supportsWebSocket: true,
    supportsAuthenticatedAccount: true,
    supportsSpot: true,
    supportsPerpetuals: true,
    supportsFutures: true,
    supportsFundingRates: true,
    supportsOpenInterest: true,
    supportsLiquidations: true,
    supportsOrderBook: true,
    supportsTrades: true,
    supportsCandles: true,
    supportsTickers: true,
    supportsHistorical: true,
    supportedIntervals: ['1m', '5m', '15m', '30m', '60m', '1d'],
    quoteMode: 'live',
    rateLimitProfile: 'Exchange rate-limits; public WS + REST weight model.',
    dataFreshnessProfile: 'Realtime market stream for crypto pairs.',
    reliabilityTier: 'high',
    notes: 'Primary authenticated crypto provider; execution remains simulation-gated.',
  },
  bybit: {
    providerId: 'bybit',
    displayName: 'Bybit (Public)',
    authMode: 'none',
    assetClasses: ['crypto'],
    supportsRest: true,
    supportsWebSocket: true,
    supportsAuthenticatedAccount: false,
    supportsSpot: true,
    supportsPerpetuals: true,
    supportsFutures: true,
    supportsFundingRates: true,
    supportsOpenInterest: true,
    supportsLiquidations: true,
    supportsOrderBook: true,
    supportsTrades: true,
    supportsCandles: true,
    supportsTickers: true,
    supportsHistorical: true,
    supportedIntervals: ['1m', '5m', '15m', '30m', '60m', '1d'],
    quoteMode: 'live',
    rateLimitProfile: 'Public market-data limits; derivatives channels prioritized.',
    dataFreshnessProfile: 'Realtime derivatives/orderflow enrichment.',
    reliabilityTier: 'standard',
    notes: 'Public-only derivatives intelligence source.',
  },
  okx: {
    providerId: 'okx',
    displayName: 'OKX (Public)',
    authMode: 'none',
    assetClasses: ['crypto'],
    supportsRest: true,
    supportsWebSocket: true,
    supportsAuthenticatedAccount: false,
    supportsSpot: true,
    supportsPerpetuals: true,
    supportsFutures: true,
    supportsFundingRates: true,
    supportsOpenInterest: true,
    supportsLiquidations: true,
    supportsOrderBook: true,
    supportsTrades: true,
    supportsCandles: true,
    supportsTickers: true,
    supportsHistorical: true,
    supportedIntervals: ['1m', '5m', '15m', '30m', '60m', '1d'],
    quoteMode: 'live',
    rateLimitProfile: 'Public channel and REST interval limits.',
    dataFreshnessProfile: 'Realtime derivatives/orderbook intelligence.',
    reliabilityTier: 'standard',
    notes: 'Public-only derivatives and funding context.',
  },
  coinbase: {
    providerId: 'coinbase',
    displayName: 'Coinbase (Public)',
    authMode: 'none',
    assetClasses: ['crypto'],
    supportsRest: true,
    supportsWebSocket: true,
    supportsAuthenticatedAccount: false,
    supportsSpot: true,
    supportsPerpetuals: false,
    supportsFutures: false,
    supportsFundingRates: false,
    supportsOpenInterest: false,
    supportsLiquidations: false,
    supportsOrderBook: true,
    supportsTrades: true,
    supportsCandles: true,
    supportsTickers: true,
    supportsHistorical: true,
    supportedIntervals: ['1m', '5m', '15m', '30m', '60m', '1d'],
    quoteMode: 'live',
    rateLimitProfile: 'Public feed limits with heartbeat channel.',
    dataFreshnessProfile: 'Realtime US spot reference pricing.',
    reliabilityTier: 'standard',
    notes: 'US spot reference pricing source.',
  },
  finnhub: {
    providerId: 'finnhub',
    displayName: 'Finnhub',
    authMode: 'api-key',
    assetClasses: ['stock', 'etf', 'crypto', 'fx', 'index'],
    supportsRest: true,
    supportsWebSocket: true,
    supportsAuthenticatedAccount: false,
    supportsSpot: true,
    supportsPerpetuals: false,
    supportsFutures: false,
    supportsFundingRates: false,
    supportsOpenInterest: false,
    supportsLiquidations: false,
    supportsOrderBook: false,
    supportsTrades: false,
    supportsCandles: true,
    supportsTickers: true,
    supportsHistorical: true,
    supportedIntervals: ['1m', '5m', '15m', '30m', '60m', '1d'],
    quoteMode: 'live',
    rateLimitProfile: 'API key quota model.',
    dataFreshnessProfile: 'Near realtime quote snapshots for stocks/ETFs.',
    reliabilityTier: 'high',
    notes: 'Primary authenticated stocks/ETFs quote provider.',
  },
  polygon: {
    providerId: 'polygon',
    displayName: 'Polygon',
    authMode: 'api-key',
    assetClasses: ['stock', 'etf', 'index'],
    supportsRest: true,
    supportsWebSocket: true,
    supportsAuthenticatedAccount: false,
    supportsSpot: true,
    supportsPerpetuals: false,
    supportsFutures: false,
    supportsFundingRates: false,
    supportsOpenInterest: false,
    supportsLiquidations: false,
    supportsOrderBook: false,
    supportsTrades: true,
    supportsCandles: true,
    supportsTickers: true,
    supportsHistorical: true,
    supportedIntervals: ['1m', '5m', '15m', '30m', '60m', '1d'],
    quoteMode: 'delayed',
    rateLimitProfile: 'API key plan quota model.',
    dataFreshnessProfile: 'Strong historical OHLCV aggregation.',
    reliabilityTier: 'high',
    notes: 'Primary historical aggregation provider for equities/ETFs.',
  },
  'twelve-data': {
    providerId: 'twelve-data',
    displayName: 'Twelve Data',
    authMode: 'api-key',
    assetClasses: ['stock', 'etf', 'crypto', 'fx', 'index'],
    supportsRest: true,
    supportsWebSocket: true,
    supportsAuthenticatedAccount: false,
    supportsSpot: true,
    supportsPerpetuals: false,
    supportsFutures: false,
    supportsFundingRates: false,
    supportsOpenInterest: false,
    supportsLiquidations: false,
    supportsOrderBook: false,
    supportsTrades: false,
    supportsCandles: true,
    supportsTickers: true,
    supportsHistorical: true,
    supportedIntervals: ['1m', '5m', '15m', '30m', '60m', '1d'],
    quoteMode: 'delayed',
    rateLimitProfile: 'API key quota.',
    dataFreshnessProfile: 'Fallback mixed-asset time-series feed.',
    reliabilityTier: 'standard',
    notes: 'Fallback provider.',
  },
  coingecko: {
    providerId: 'coingecko',
    displayName: 'CoinGecko',
    authMode: 'api-key',
    assetClasses: ['crypto'],
    supportsRest: true,
    supportsWebSocket: false,
    supportsAuthenticatedAccount: false,
    supportsSpot: true,
    supportsPerpetuals: false,
    supportsFutures: false,
    supportsFundingRates: false,
    supportsOpenInterest: false,
    supportsLiquidations: false,
    supportsOrderBook: false,
    supportsTrades: false,
    supportsCandles: true,
    supportsTickers: true,
    supportsHistorical: true,
    supportedIntervals: ['1d'],
    quoteMode: 'cached',
    rateLimitProfile: 'API key tiers with request quotas.',
    dataFreshnessProfile: 'Delayed/aggregated crypto data.',
    reliabilityTier: 'standard',
    notes: 'Fallback crypto quote/history provider.',
  },
  eodhd: {
    providerId: 'eodhd',
    displayName: 'EODHD',
    authMode: 'api-key',
    assetClasses: ['stock', 'etf', 'crypto', 'fx', 'index'],
    supportsRest: true,
    supportsWebSocket: false,
    supportsAuthenticatedAccount: false,
    supportsSpot: true,
    supportsPerpetuals: false,
    supportsFutures: false,
    supportsFundingRates: false,
    supportsOpenInterest: false,
    supportsLiquidations: false,
    supportsOrderBook: false,
    supportsTrades: false,
    supportsCandles: true,
    supportsTickers: true,
    supportsHistorical: true,
    supportedIntervals: ['1d'],
    quoteMode: 'delayed',
    rateLimitProfile: 'API key request quota.',
    dataFreshnessProfile: 'Mostly daily/lagging snapshots.',
    reliabilityTier: 'standard',
    notes: 'Legacy fallback provider.',
  },
  tiingo: {
    providerId: 'tiingo',
    displayName: 'Tiingo',
    authMode: 'api-key',
    assetClasses: ['stock', 'etf'],
    supportsRest: true,
    supportsWebSocket: false,
    supportsAuthenticatedAccount: false,
    supportsSpot: true,
    supportsPerpetuals: false,
    supportsFutures: false,
    supportsFundingRates: false,
    supportsOpenInterest: false,
    supportsLiquidations: false,
    supportsOrderBook: false,
    supportsTrades: false,
    supportsCandles: true,
    supportsTickers: false,
    supportsHistorical: true,
    supportedIntervals: ['1d'],
    quoteMode: 'cached',
    rateLimitProfile: 'API key request quota.',
    dataFreshnessProfile: 'Metadata/fundamentals and daily history.',
    reliabilityTier: 'standard',
    notes: 'Metadata-focused fallback.',
  },
  'world-bank': {
    providerId: 'world-bank',
    displayName: 'World Bank Indicators API',
    authMode: 'none',
    assetClasses: ['index'],
    supportsRest: true,
    supportsWebSocket: false,
    supportsAuthenticatedAccount: false,
    supportsSpot: false,
    supportsPerpetuals: false,
    supportsFutures: false,
    supportsFundingRates: false,
    supportsOpenInterest: false,
    supportsLiquidations: false,
    supportsOrderBook: false,
    supportsTrades: false,
    supportsCandles: false,
    supportsTickers: false,
    supportsHistorical: true,
    supportedIntervals: ['1d'],
    quoteMode: 'cached',
    rateLimitProfile: 'Public API; fair-use limits.',
    dataFreshnessProfile: 'Mostly annual or periodic macroeconomic releases.',
    reliabilityTier: 'high',
    notes: 'Simulation-safe macro context only. No execution path.',
  },
  ecb: {
    providerId: 'ecb',
    displayName: 'ECB Data Portal',
    authMode: 'none',
    assetClasses: ['fx', 'index'],
    supportsRest: true,
    supportsWebSocket: false,
    supportsAuthenticatedAccount: false,
    supportsSpot: false,
    supportsPerpetuals: false,
    supportsFutures: false,
    supportsFundingRates: false,
    supportsOpenInterest: false,
    supportsLiquidations: false,
    supportsOrderBook: false,
    supportsTrades: false,
    supportsCandles: false,
    supportsTickers: false,
    supportsHistorical: true,
    supportedIntervals: ['1d'],
    quoteMode: 'cached',
    rateLimitProfile: 'Public SDMX endpoint limits.',
    dataFreshnessProfile: 'Daily to monthly macro and rates data.',
    reliabilityTier: 'high',
    notes: 'Simulation-safe macro context only. No execution path.',
  },
  fred: {
    providerId: 'fred',
    displayName: 'FRED',
    authMode: 'api-key',
    assetClasses: ['index'],
    supportsRest: true,
    supportsWebSocket: false,
    supportsAuthenticatedAccount: false,
    supportsSpot: false,
    supportsPerpetuals: false,
    supportsFutures: false,
    supportsFundingRates: false,
    supportsOpenInterest: false,
    supportsLiquidations: false,
    supportsOrderBook: false,
    supportsTrades: false,
    supportsCandles: false,
    supportsTickers: false,
    supportsHistorical: true,
    supportedIntervals: ['1d'],
    quoteMode: 'cached',
    rateLimitProfile: 'API key quota model.',
    dataFreshnessProfile: 'Daily to quarterly U.S. macro time-series.',
    reliabilityTier: 'high',
    notes: 'Simulation-safe macro context only. No execution path.',
  },
  'local-cache': {
    providerId: 'local-cache',
    displayName: 'Local Cache',
    authMode: 'none',
    assetClasses: ['stock', 'etf', 'crypto', 'fx', 'index'],
    supportsRest: false,
    supportsWebSocket: false,
    supportsAuthenticatedAccount: false,
    supportsSpot: true,
    supportsPerpetuals: false,
    supportsFutures: false,
    supportsFundingRates: false,
    supportsOpenInterest: false,
    supportsLiquidations: false,
    supportsOrderBook: false,
    supportsTrades: false,
    supportsCandles: true,
    supportsTickers: true,
    supportsHistorical: true,
    supportedIntervals: ['1d'],
    quoteMode: 'cached',
    rateLimitProfile: 'No external quota; internal persistence limits apply.',
    dataFreshnessProfile: 'Fallback snapshots only.',
    reliabilityTier: 'standard',
    notes: 'Used only for degraded fallback reads.',
  },
};

export function getProviderCapabilities(providerId: UnifiedProviderId): ProviderCapabilities {
  return CAPS[providerId];
}

export function listProviderCapabilities(): ProviderCapabilities[] {
  return Object.values(CAPS);
}
