import Link from 'next/link';
import { Section } from '../../../components/ui/section';

export const metadata = {
  title: 'Risk Disclosure — Aurox Intelligence',
  description: 'Risk and simulation disclosures for the Aurox Intelligence investment simulation and signal analytics features.',
};

export default function RiskDisclosurePage() {
  return (
    <>
      <Section className="dashboard-section dashboard-section--hero">
        <div className="workstation-page-header">
          <div className="section__eyebrow">Legal · Risk Disclosure</div>
          <h1 className="workstation-page-header__title">Risk Disclosure & Simulation Notice</h1>
          <p className="workstation-page-header__description">
            Last updated: April 2026. This disclosure covers the simulated nature of investment features and the inherent limitations of algorithmic analysis.
          </p>
        </div>
      </Section>

      <Section className="dashboard-section">
        <div className="legal-prose">
          <section className="legal-prose__section legal-prose__section--highlight">
            <h2>Simulation only — no real money</h2>
            <p>
              <strong>All investment, portfolio, and trading features on this Platform operate in simulation mode only.</strong> No real money is invested, no real brokerage orders are placed, and no regulated financial services of any kind are performed. Virtual funds used in simulations have no monetary value and cannot be withdrawn, transferred, or exchanged.
            </p>
          </section>

          <section className="legal-prose__section">
            <h2>1. Not investment advice</h2>
            <p>
              Signal outputs, directional forecasts, and model-generated analytics produced by this Platform are for informational and analytical purposes only. They do not constitute investment advice, investment recommendations, or personalised financial guidance. You must not make real investment decisions based solely on Platform outputs.
            </p>
            <p>
              Before making any real investment decision, you should consult a qualified and regulated financial adviser who can assess your specific circumstances, financial goals, and risk tolerance.
            </p>
          </section>

          <section className="legal-prose__section">
            <h2>2. Nature of algorithmic signals</h2>
            <p>
              Signals and forecasts on this Platform are generated by quantitative models applied to historical and live market data. These models carry inherent limitations:
            </p>
            <ul>
              <li>Models are trained on historical data. Past market patterns do not reliably predict future behaviour.</li>
              <li>Signal confidence scores represent model-internal estimates, not probabilities of real-world outcomes.</li>
              <li>Models may be incorrect, miscalibrated, or fail during market stress conditions.</li>
              <li>The models do not incorporate fundamental analysis, corporate events, or macroeconomic variables unless explicitly described.</li>
              <li>Market conditions, liquidity, and correlations can shift rapidly in ways that invalidate any model assumption.</li>
            </ul>
          </section>

          <section className="legal-prose__section">
            <h2>3. Market data limitations</h2>
            <p>
              Market data displayed on the Platform is sourced from third-party providers and may be subject to delays, errors, gaps, or temporary unavailability. The Platform does not guarantee the accuracy, completeness, or real-time nature of any market data shown. Prices, quotes, and other market data are provided for informational purposes and do not represent executable prices or official exchange data.
            </p>
          </section>

          <section className="legal-prose__section">
            <h2>4. Simulated portfolio performance</h2>
            <p>
              Simulated portfolio results shown on this Platform do not represent actual investment performance. Simulated returns:
            </p>
            <ul>
              <li>Do not account for transaction costs, slippage, bid-ask spreads, or market impact</li>
              <li>Do not account for taxes, regulatory fees, or custody charges</li>
              <li>May assume execution at prices that would not be achievable in a real market</li>
              <li>Are not indicative of future real-money performance</li>
            </ul>
          </section>

          <section className="legal-prose__section">
            <h2>5. Asset-class specific risks</h2>
            <h3>Equities and ETFs</h3>
            <p>
              Equity and ETF markets can experience significant volatility including rapid price declines, trading halts, liquidity crises, and prolonged drawdown periods. ETFs may trade at a premium or discount to their underlying net asset value.
            </p>
            <h3>Cryptocurrencies</h3>
            <p>
              Crypto assets are highly speculative and subject to extreme volatility, regulatory uncertainty, technological risk, and liquidity risk. Crypto markets operate 24/7 including weekends and holidays. The value of crypto assets may fall to zero. Crypto coverage on this Platform is for informational purposes and does not recommend speculative positions.
            </p>
            <h3>Foreign exchange</h3>
            <p>
              Foreign exchange markets operate with high leverage in real-world contexts and can move rapidly in response to economic data, central bank actions, and geopolitical events. FX data on this Platform is for analytical observation only.
            </p>
          </section>

          <section className="legal-prose__section">
            <h2>6. No regulatory status</h2>
            <p>
              Aurox Intelligence is not a regulated financial institution, investment firm, broker-dealer, or registered investment adviser. The Platform does not hold any financial services licence and does not provide regulated services. If you require regulated financial services, please consult a licensed provider in your jurisdiction.
            </p>
          </section>
        </div>

        <nav className="legal-prose__nav" aria-label="Legal navigation">
          <Link href="/legal/privacy" className="module-panel__link">← Privacy Policy</Link>
          <Link href="/legal/imprint" className="module-panel__link">Legal Notice →</Link>
        </nav>
      </Section>
    </>
  );
}
